### ISSUE TITLE
Fails to translate the libc crate

### ISSUE THREAD

**Issue by atomb** [GaloisInc/mir-json#11]
The `libc` crate has a custom `build.rs` file that causes trouble with `mir-json`. In particular, it has custom code to identify the compiler version which fails when the compiler is `mir-json`. See here:

https://github.com/rust-lang/libc/blob/a17a91cdbf13a43af4e24c0f5498ff6a5e6271c5/build.rs#L7

**Comment by RyanGlScott** [comment]
I don't believe this is an issue with the current version of `mir-json` + the version of `libc` that is shipped with modern `crux-mir`, as the translation script is able to handle `libc` without issues. Please reopen this issue if I am overlooking something.
