### ISSUE TITLE
Print json files with newlines

### ISSUE THREAD

**Issue by sauclovian-g** [GaloisInc/mir-json#68]
Currently the linked-mir.json file that comes out is one enormous line. While this is perfectly valid json, it's unnecessarily irritating to deal with if you need to look in it. (For example, ```less``` has behavior with adverse time complexity on long lines, and ```grep``` and other shell tools work on a line-by-line basis.)

If there's a way to generate it with newlines, that would be worth turning on. Doesn't necessarily need to be indented (since that probably wastes noticeable amounts of space)...

**Comment by RyanGlScott** [comment]
I'm reluctant to do this, since this would noticeably increase the amount of space needed for MIR JSON files in the common case. I think that if users want to pretty-print MIR JSON, they should use a tool like [`jq`](https://jqlang.github.io/jq/) to do so.

**Comment by sauclovian-g** [comment]
After chewing this over for a while, I think you're right. We should treat the json blobs like object files; they're expected to be opaque but some tooling is available for looking at them when things go off. I think what this means is that we ought to have a dumper tool for them. Sometime. (In the long run jg is probably not adequate on its own, if only because it requires the user to know the schema.)
